Blumio/config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  get 'home'    => 'static_pages#home'
  get 'search'  => 'events#searchAll'
  post 'search' => 'events#search'
  get 'searchList' => 'events#searchListAll'
  post 'searchList' => 'events#searchList'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  post 'events_people/:id' => 'events#join'
  delete 'events_people/:id' => 'events#leave'
  post 'events/new' => 'events#create'

  put 'forgot_password' => 'sessions#send_password_reset_instructions'

  get 'password_reset' => 'sessions#password_reset'
  put 'password_reset' => 'sessions#new_password'

  post 'persons/:id' => 'persons#parse_update'
  get 'persons/:id' => 'persons#show'

  match '/404', to: 'static_pages#404', via: :all
  match '/422', to: 'static_pages#404', via: :all
  match '/500', to: 'static_pages#404', via: :all

  resources :events
  resources :persons

  root 'static_pages#home'
  

end

Blumio/app/views/layouts/_head.html.erb
<head>

	<title>Blumio, your Sports Mate Finder</title>

    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag params[:controller] %>
    <%= stylesheet_link_tag params[:controller] %>
    <link href="../stylesheets/sports.css" rel="stylesheet">
    <link href="../stylesheets/font-awesome.css" rel="stylesheet">
	<meta charset="UTF-8">
	<meta http-equiv="Content-type" content="text/html; charset=UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <!-- protect against CRSF attacks (related with protect_from_forgery with: :exception in application controller-->
    <%= csrf_meta_tags %>

</head>

Blumio/app/views/layouts/_navbar.html.erb
<!-- has to be corrected in all files -->
<nav class="navbar navbar-bordeaux navbar-fixed-top vertical-center" role="navigation">
	<div class="container vertical-center margin-left-2" href="#">
		<a href="#menu-toggle" id="menu-toggle" class="without-underline">
			<span class="fa fa-bars"> </span>
			<div class="text div-nav"> <img src="../img/logo2.png" class="logo"></div>
		</a>
	</div>
        <div class="dropdown nav navbar-nav navbar-left">
            <a id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="#">
                <i class="fa fa-bell"></i>
            </a>
            <ul class="dropdown-menu notifications pull-right" role="menu" aria-labelledby="dLabel">
                <div class="notifications-wrapper">
                    <% for activity in current_person.activities.first(4) %>
                        <li><%= render_activity(activity) %></li>
                    <% end %>
                </div>
                <li class="divider"></li>
                <div class="notification-footer"><a href="<%= notifications_index_path %>"><h4 class="menu-title">Ver todas<i class="glyphicon glyphicon-circle-arrow-right"></i></h4></a></div>
            </ul>

        </div>
</nav>

Blumio/app/views/layouts/_participantes.html.erb
<% @event.persons.each do |person| %>
    <div class="col-xs-2 col-sm-1">
      <%= link_to person, class: "thumbnail" do %>
          <center><span><%= person.first_name %></span></center>
          <div class="image">
            <img src="<%= person.image %>" class="img img-responsive full-width img-circle" />
          </div>
      <% end %>
    </div>
<% end %>

Blumio/app/views/layouts/_searchBarList.html.erb
<div class="col-xs-3 col-md-1 searchIcons">


  <%= form_tag("/searchList", method: "post") do %>
      <div id="data" class="text-left searchBar-wrapper">
        <ul class="sidebar-nav text-left">
          <li style="margin-top: 5%">
            <a onclick="hideData();"> <span class="fa fa-chevron-right icone-barra-lateral"></span></a>
          </li>
        </ul>
        <br>
        <br>

        <div class="radio">
          <label><input value="data" onchange="showDataSelection()" type="radio" name="dataFilter">Escolher datas</label>
        </div>
        <div id="dataSelection" style="display: none ; with: 100%">
          A partir de:<br>
          <input name="timeLowerLimit" class="form-control" type="date" />
          <br>
          Até:<br>
          <input name="timeUpperLimit" class="form-control" type="date" />
          <br>
        </div>

        <div class="radio">
          <label><input value="hoje" onchange="hideDataSelection()" type="radio" name="dataFilter">Hoje</label>
        </div>
        <div class="radio">
          <label><input value="amanha" onchange="hideDataSelection()" type="radio" name="dataFilter">Amanhã</label>
        </div>
        <div class="radio">
          <label><input value="proxSemana" onchange="hideDataSelection()" type="radio" name="dataFilter">Proximos 7 dias</label>
        </div>


      </div>

      <div id="desporto" class="searchBar-wrapper">
        <ul class="sidebar-nav text-left">
          <li style="margin-top: 5%">
            <a onclick="hideDesporto();"> <span class="fa fa-chevron-right icone-barra-lateral"></span></a>
          </li>
        </ul>

        <br>
        <br>
        <% @sports.each do |sport| %>
            <label style="font-size: 30px"><input type="radio" name="desportoId" value="<%= sport.id %>"><a class="nounderline  <%= sport.icon %>"></a> </label>
            <br>
            <br>
        <% end %>

      </div>

      <div id="adesao" class="searchBar-wrapper">
        <ul class="sidebar-nav text-left">
          <li style="margin-top: 5%">
            <a onclick="hideAdesao();"> <span class="fa fa-chevron-right icone-barra-lateral"></span></a>
          </li>
        </ul>

        <br>
        <br>
        Minimo:<br>
        <input name="numMinParticipantes" class="form-control" type="number" min="0" />
        <br>
        Maximo:<br>
        <input name="numMaxParticipantes" class="form-control" type="number" min="0"/>
      </div>

      <div id="pertoDeMim" class="searchBar-wrapper">
        <ul class="sidebar-nav text-left">
          <li style="margin-top: 5%">
            <a onclick="hidePertoDeMim();"> <span class="fa fa-chevron-right icone-barra-lateral"></span></a>
          </li>
        </ul>

        <br>
        <br>
        <div class="radio">
          <label><input value="nao" onchange="hideLocationSelection()" type="radio" name="localizacao">Nao usar</label>
        </div>
        <div class="radio">
          <label><input value="sim" onchange="showLocationSelection();getLocationPesquisa();" type="radio" name="localizacao">Usar</label>
        </div>
        <div id="locationSelection" style="display: none ; with: 100%">
          Num raio de (km):<br>
          <input name="raioLocal" class="form-control" type="number" min="1"/>
          <br>
          <p id="demo"></p>
          <input id="lat" type="hidden" name="lat" value="">
          <input id="lon" type="hidden" name="lon" value="">
          <div id="holder" style="width: 230px; margin-left: auto; margin-right: auto">
            <div id="mapholder" ></div>
          </div>

        </div>
      </div>





      <div class="row align-horizontal-center" onclick="showDataForm();">
        <i class="fa fa-calendar"></i> <span>Data</span>
      </div>
      <div class="row align-horizontal-center" onclick="showDesportoForm();">
        <i class="sports-basketball3"></i> <span>Desporto</span>
      </div>
      <div class="row align-horizontal-center" onclick="showAdesaoForm();">
        <i class="fa fa-bar-chart-o"></i> <span>Adesão</span>
      </div>
      <div class="row align-horizontal-center" onclick="showPertoDeMimForm();">
        <i class="fa fa-map-marker"></i> <span>Perto de Mim</span>
      </div>

      <div class="row align-horizontal-center">
        <button style="width: 80%;" class="botaoPesquisa" type="submit"><span class="fa fa-search fa-2x"></span></button>
      </div>



  <% end %>
  <div class="row align-horizontal-center">
    <%= form_tag(searchList_path) do %>
        <button style="width: 80%;" class="botaoPesquisa" type="submit">Ver Todos</button>
    <% end %>
  </div>

  <div class="row align-horizontal-center">
    <%= form_tag( search_path) do %>
        <button style="width: 80%;" class="botaoPesquisa" type="submit"><span class="fa fa-globe  fa-2x"></span></button>
    <% end %>
  </div>
</div>

Blumio/app/views/layouts/_searchBarMap.html.erb
<div class="col-xs-3 col-md-1 searchIcons">


  <%= form_tag("/search", method: "post") do %>
      <div id="data" class="text-left searchBar-wrapper">
        <ul class="sidebar-nav text-left">
          <li style="margin-top: 5%">
            <a onclick="hideData();"> <span class="fa fa-chevron-right icone-barra-lateral"></span></a>
          </li>
        </ul>
        <br>
        <br>

        <div class="radio">
          <label><input value="data" onchange="showDataSelection()" type="radio" name="dataFilter">Escolher datas</label>
        </div>
        <div id="dataSelection" style="display: none ; with: 100%">
          A partir de:<br>
          <input name="timeLowerLimit" class="form-control" type="date" />
          <br>
          Até:<br>
          <input name="timeUpperLimit" class="form-control" type="date" />
          <br>
        </div>

        <div class="radio">
          <label><input value="hoje" onchange="hideDataSelection()" type="radio" name="dataFilter">Hoje</label>
        </div>
        <div class="radio">
          <label><input value="amanha" onchange="hideDataSelection()" type="radio" name="dataFilter">Amanhã</label>
        </div>
        <div class="radio">
          <label><input value="proxSemana" onchange="hideDataSelection()" type="radio" name="dataFilter">Proximos 7 dias</label>
        </div>


      </div>

      <div id="desporto" class="searchBar-wrapper">
        <ul class="sidebar-nav text-left">
          <li style="margin-top: 5%">
            <a onclick="hideDesporto();"> <span class="fa fa-chevron-right icone-barra-lateral"></span></a>
          </li>
        </ul>

        <br>
        <br>
        <% @sports.each do |sport| %>
            <label style="font-size: 30px"><input type="radio" name="desportoId" value="<%= sport.id %>"><a class="nounderline  <%= sport.icon %>"></a> </label>
            <br>
            <br>
        <% end %>

      </div>

      <div id="adesao" class="searchBar-wrapper">
        <ul class="sidebar-nav text-left">
          <li style="margin-top: 5%">
            <a onclick="hideAdesao();"> <span class="fa fa-chevron-right icone-barra-lateral"></span></a>
          </li>
        </ul>

        <br>
        <br>
        Minimo:<br>
        <input name="numMinParticipantes" class="form-control" type="number" min="0" />
        <br>
        Maximo:<br>
        <input name="numMaxParticipantes" class="form-control" type="number" min="0"/>
      </div>

      <div id="pertoDeMim" class="searchBar-wrapper">
        <ul class="sidebar-nav text-left">
          <li style="margin-top: 5%">
            <a onclick="hidePertoDeMim();"> <span class="fa fa-chevron-right icone-barra-lateral"></span></a>
          </li>
        </ul>

        <br>
        <br>
        <div class="radio">
          <label><input value="nao" onchange="hideLocationSelection()" type="radio" name="localizacao">Nao usar</label>
        </div>
        <div class="radio">
          <label><input value="sim" onchange="showLocationSelection();getLocationPesquisa();" type="radio" name="localizacao">Usar</label>
        </div>
        <div id="locationSelection" style="display: none ; with: 100%">
          Num raio de (km):<br>
          <input name="raioLocal" class="form-control" type="number" min="1"/>
          <br>
          <p id="demo"></p>
          <input id="lat" type="hidden" name="lat" value="">
          <input id="lon" type="hidden" name="lon" value="">
          <div id="holder" style="width: 230px; margin-left: auto; margin-right: auto">
            <div id="mapholder" ></div>
          </div>

        </div>
      </div>




  <div class="row align-horizontal-center" onclick="showDataForm();">
    <i class="fa fa-calendar"></i> <span>Data</span>
  </div>
  <div class="row align-horizontal-center" onclick="showDesportoForm();">
    <i class="sports-basketball3"></i> <span>Desporto</span>
  </div>
  <div class="row align-horizontal-center" onclick="showAdesaoForm();">
    <i class="fa fa-bar-chart-o"></i> <span>Adesão</span>
  </div>
  <div class="row align-horizontal-center" onclick="showPertoDeMimForm();">
    <i class="fa fa-map-marker"></i> <span>Perto de Mim</span>
  </div>



      <div class="row align-horizontal-center">
        <button style="width: 80%;" class="botaoPesquisa" type="submit"><span class="fa fa-search fa-2x"></span></button>
      </div>

  <% end %>

  <div class="row align-horizontal-center">
    <%= form_tag(search_path) do %>
        <button style="width: 80%;" class="botaoPesquisa" type="submit">Ver Todos</button>
    <% end %>
  </div>

  <div class="row align-horizontal-center">
    <%= form_tag(searchList_path) do %>

        <button style="width: 80%;" class="botaoPesquisa" type="submit"><span class="fa fa-list-alt fa-2x"></span></button>
    <% end %>
  </div>
</div>

Blumio/app/views/layouts/_sidebar.html.erb
<!-- Sidebar -->
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
      <div class="row">
          <li class="sidebar-brand">
              <img src="<%= current_person.image %>" class="img-responsive img-circle pull-left userImage">
              <%= link_to current_person.full_name, current_person , style: 'min-height: 65px; padding-top: 9px' %>
          </li>
      </div>
    <li>
      <a data-no-turbolink="true" href=<%= root_path %>> <span class="fa fa-home icone-barra-lateral"></span>Início</a>
    </li>

    <li>
      <a data-no-turbolink="true" href="#"> <span class="fa fa-book icone-barra-lateral"></span>Eventos</a>
    </li>
    <li>
      <a id="idMeusEventos" data-no-turbolink="true" href="#"> &nbsp&nbsp&nbsp <span class="fa fa-user icone-barra-lateral"></span>Meus</a>
      <%= form_tag("/searchList", method: "post",id: "formMeusEventos") do %>
          <input type="hidden" name="criador" value="true">
      <% end %>
    </li>
    <li>
      <a data-no-turbolink="true" href=<%= search_path %>>&nbsp&nbsp&nbsp <span class="fa fa-search icone-barra-lateral"></span>Procurar</a>
    </li>
    <li>
      <a data-no-turbolink="true" href=<%= new_event_path %>>&nbsp&nbsp&nbsp <span class="fa fa-plus-circle icone-barra-lateral"></span>Criar</a>
    </li>
    <li>
      <a data-no-turbolink="true" href="<%= logout_path %>" data-method="delete" rel="nofollow"> <span class="fa fa-sign-out icone-barra-lateral"></span>Sair</a>
    </li>
  </ul>


</div>
<script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });

    document.getElementById("idMeusEventos").onclick = function() {
        document.getElementById("formMeusEventos").submit();
    }
</script>
<!-- /#sidebar-wrapper -->

Blumio/app/views/layouts/application.html.erb
<%= yield %>